app:
  name: "webapp"
  mode: "dev"
  port: 8081
  start_time: "2021-09-01"
  machine_id: 12
log:
  level: "debug"
  filename: "webapp.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  driver: "mysql"
  port: 3306
  user: "root"
  password: "asd456"
  db_name: "db"
  db_charset: "utf8mb4"
  db_prefix: ""
  db_collation: "utf8mb4_unicode_ci"
  max_idle_conns: 10
  max_open_conns: 100
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10